### ISSUE TITLE
can't enable canonical livepatch

### ISSUE THREAD

**Issue by geneafisher** [ubuntudesign/www.ubuntu.com#1034]
## Summary
went to Canonical Livepatch Service, got my token, installed snapd, then installed canonical-livepatch, but when I ran the next command, canonical-livepatch enable . . . (the token),  I got: "cannot change apparmor hat of the support process for mount namespace capture. errmsg: Operation not permitted"

[please describe the issue]
I am running Linux Mint 18 kernel 4.4.0-43-generic- ubuntu 16.04 xenial
## Process
I plan to reboot to kernel 4.4.0-44 (it was installed on a recent update) to see if that fixes the problem
[list the steps to replicate the issue]

## Current and expected result
I ran canonical-livepatch status and got "canonical-livepatch command not found"
[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
@geneafisher sorry this has taken me so long to get back to you, but you will need to re-file the bug here: https://bugs.launchpad.net/canonical-livepatch-client/+filebug however, I assume it is because you are on Mint and the changes to the OS haven't made it into it yet.

Peter
