### ISSUE TITLE
Trusty release section download files do not match descriptions

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [ubuntudesign/www.ubuntu.com#1041]
I have just noticed that in the Trusty release section: http://releases.ubuntu.com/trusty/ The file names do not match the descriptions for many of the files. This one for instance (the rest follow a similar pattern):

> ubuntu-14.04.**4**-desktop-amd64.iso         17-Feb-2016 23:42  1.0G  Ubuntu 14.04.**5** LTS (Trusty Tahr)

**Comment by pmahnke** [comment]
Thanks @seventhsonofaseventhson

I spoke to the release team, it is because they are about to rotate the 14.04.4 off the server in favour of the .5... 

> mostly harmless and i think that has always been like that.
> it will look right if and when .4 images are rotated off to old-releases host.
> or maybe infinity can twiddle things
