### ISSUE TITLE
No “Networks” tab in MAAS Version 1.9 as per documentation

### ISSUE THREAD

**Issue by davecore82** [ubuntudesign/www.ubuntu.com#1043]
## Summary
The https://www.ubuntu.com/download/cloud Autopilot instructions say this for Step 3 Install MAAS:

> Go to the “Networks” tab and for each of the networks auto-created, click “Edit network” to add the default gateway and DNS server details

There is no Networks tab in MAAS 1.9 (which is the MAAS version you get by following the instructions on the page).

## Screenshot

![screenshotmaas](https://cloud.githubusercontent.com/assets/3519585/19782413/cb068b04-9c5b-11e6-8f89-4e7696a1c626.png)

**Comment by pmahnke** [comment]
@davecore82 

thanks for letting us know, but since this is ultimately this is an Autopilot issue... I have filed 
[a bug](https://bugs.launchpad.net/landscape/+bug/1637521) against that project to help resolve the issue.

I will close this bug here.
