### ISSUE TITLE
Error Submitting Authentication when Requesting Token

### ISSUE THREAD

**Issue by Nerdfest** [ubuntudesign/www.ubuntu.com#1050]
## Summary
Submitting a request for a token for Live patch causes a server error.
## Process

- Logged in with both existing and newly created UbuntuOne account.  
- Selected "Ubuntu User"
- Selected "Get your token".

The submit briefly went to `login.ubuntu.com`, then to a "**Server Error (500)**" on `auth.livepatch.canonical.com`.

The rest of the path looks like typical authentication stuff: (`/openid/complete/?next=%2F%3Fuser_type%3Dubuntu-user&janrain_nonce=2016-11-01T02%3A28%3A05ZXlu8pM`) as an example ... I'll assume that none is expired now of course.

I've tried this on both FireFox and Chrome under Kubuntu 16.04.

## Current and expected result

I would expect to be direct to a token generation page or something similar. Current I only get a "Server Error (500)"

**Comment by nottrobin** [comment]
Thanks @nakedhitman for reporting this.

There is now a public bug list [over at lp:livepatch-auth](https://bugs.launchpad.net/livepatch-auth). Would you mind refiling your bug over there?

**Comment by nottrobin** [comment]
@Nerdfest for the record, I've just got this response from the livepatch team:

> I've diagnosed the problem with folks getting 500 errors on livepatch. To summarize, their Launchpad usernames are too long and are hitting a bug on livepatch. We're working on it, but a workaround is to change their username so it's shorter
> usernames shorter than 30 chars should work fine for now, but we'll have this fixed soon so it'll no longer be an issue

**Comment by Nerdfest** [comment]
Thanks. My username i pretty short, for at least one of the accounts I tried. Maybe long email addresses? Regardless, thanks for the tip!

**Comment by nottrobin** [comment]
@Nerdfest What's the email address?

**Comment by Nerdfest** [comment]
Actually, it's under 30 characters. I think I'm getting confused between the UbuntuOne and LaunchPad logins. I have an old account as well, where the userId is generated, and I'm getting a warning about changing it locking me out of other sites for that OpenId. I'm guessing that generated username is the problem, so I'll make sure I'm logged out of *both* UbuntuOne and LaunchPad and try a different account, or I'll change my OpenId account. Thanks for the help.
