### ISSUE TITLE
500 error when requesting livepatch key

### ISSUE THREAD

**Issue by nakedhitman** [ubuntudesign/www.ubuntu.com#1083]
## Summary

When requesting a key at https://auth.livepatch.canonical.com/, I am met with a 500 error. I chose Ubuntu Advantage, but had the same results when choosing Ubuntu User.

## Process

- Navigate to https://auth.livepatch.canonical.com/
- Select any option
- Click "Get your token"

## Current and expected result

Expected: a token
Result: 500 error

## Screenshot

There is nothing special about the error to warrant a screenshot. However, this is the full URI that it bounced me to:
https://auth.livepatch.canonical.com/openid/complete/?next=%2F%3Fuser_type%3Dubuntu-advantage-customer&janrain_nonce=2016-11-03T21%3A27%3A55Zk85YlV

**Comment by nottrobin** [comment]
Thanks @nakedhitman for reporting this.

There is now a public bug list [over at lp:livepatch-auth](https://bugs.launchpad.net/livepatch-auth). Would you mind refiling your bug over there?

**Comment by nottrobin** [comment]
@nakedhitman for the record, I've just got this response from the livepatch team:

> I've diagnosed the problem with folks getting 500 errors on livepatch. To summarize, their Launchpad usernames are too long and are hitting a bug on livepatch. We're working on it, but a workaround is to change their username so it's shorter
> usernames shorter than 30 chars should work fine for now, but we'll have this fixed soon so it'll no longer be an issue
