### ISSUE TITLE
cloud/openstack/managed-cloud: small copy updates

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/www.ubuntu.com#1104]
Some copy changes were done before the page went live:

- [x] The third block in "Your cloud, your site, our expertise" should say "virtualisation"
- [x] Add "the" in the "Download BootStack Direct brochure" link
- [x] Remove "on-demand" from last row link
- [x] Lowercase "containers" in last paragraph
- [x] The title tag of the page should be sentence case: "BootStack - your managed cloud"

**Comment by pmahnke** [comment]
I made it Watch +the+ webinar

**Comment by pmahnke** [comment]
PR #1124 fixes this... closing
