### ISSUE TITLE
phone/overview: text block in second row is cropped

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/www.ubuntu.com#1105]
## Summary

The text block in the second row (black) is cropped at the top (in some screens more than in others), on large screens.

## Screenshot

<img width="1205" alt="ubuntu-phone-overview" src="https://cloud.githubusercontent.com/assets/223966/20311779/f575b47c-ab48-11e6-904c-dc578ec4e459.png">

**Comment by pmahnke** [comment]
@yaili 

I propose removing the margin-top

.scopes-text {
    /* margin-top: -12vw; */
}

![image](https://cloud.githubusercontent.com/assets/441217/20427697/276db3b8-ad7d-11e6-8d85-b96bece95b24.png)

ok?

**Comment by yaili** [comment]
👍
