### ISSUE TITLE
Linux lower-case on https://www.ubuntu.com/support/plans-and-pricing

### ISSUE THREAD

**Issue by ChibaPet** [ubuntudesign/www.ubuntu.com#1106]
## Summary

Linux is a proper name and should be upper-cased on https://www.ubuntu.com/support/plans-and-pricing

## Process

see https://www.ubuntu.com/support/plans-and-pricing

## Current and expected result

s/linux/Linux/g

**Comment by WillMoggridge** [comment]
Thanks for pointing this out, I'll get this changed
