### ISSUE TITLE
Improve title tag of homepage

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/www.ubuntu.com#1117]
## Summary

The title tag can be improved

## Process

Open the homepage of ubuntu.com, look at the text in the browser tab

## Current and expected result

I suggest:

The leading operating system for PC, tablet, phone, cloud and server

Two changes:
- spell out OS
- add server

**Comment by pmahnke** [comment]
I think we need to add IoT as well.

How about...

The leading operating system for PCs, tablets, phones, IoT devices, servers and the cloud.

**Comment by yaili** [comment]
👍
