### ISSUE TITLE
Dead Link to an abandoned Tumblr blog

### ISSUE THREAD

**Issue by NeoTheThird** [ubuntudesign/www.ubuntu.com#1126]
## Summary

There is a dead link on the Ubuntu Phone Features site (https://www.ubuntu.com/phone/features).

## Process

When you click on "Play to learn more" in the second Paragraph, you're taken to an abandoned Tumblr blog.

## Expected result

Useful Information about Scopes.

**Comment by pmahnke** [comment]
thanks @neothethird, we were just in the process of closing the site down.

**Comment by NeoTheThird** [comment]
You're talking about the Tumblr Blog, not the "Features" site, right?

**Comment by pmahnke** [comment]
;-) yes, the scope roulette site that was a game that has ended.
