### ISSUE TITLE
livepatch returning 500 on signup

### ISSUE THREAD

**Issue by sbfl** [ubuntudesign/www.ubuntu.com#1130]
## Summary

Just tried to signup for live patches on https://auth.livepatch.canonical.com/ and got a 500 in response, nothing in the body to help so it's hard to tell what the problem is.

Just wanted to raise it in case it's a new issue.

**Comment by pmahnke** [comment]
@sbfl I just tried and the service was working.  Can you try again?  Perhaps it was a temporary error.

Best Regards,

Peter

**Comment by sbfl** [comment]
Still getting a 500

Below are the list of calls when I hit "Get Token": 
![screenshot from 2016-11-20 11-10-51](https://cloud.githubusercontent.com/assets/5642196/20464223/1ba10440-af12-11e6-8223-e5b38fb07ea1.png)

I'm assuming the response header can be useful to track the reason for the internal error in the logs: 
```
HTTP/1.1 500 INTERNAL SERVER ERROR
Date: Sun, 20 Nov 2016 16:08:53 GMT
Server: gunicorn/19.6.0
Vary: Accept-Language,Cookie
X-Frame-Options: SAMEORIGIN
Content-Type: text/html
X-Sentry-ID: bf40e72ee7db4e639256504397e4d6b5
Content-Language: en
X-Bzr-Revision-Number: 55
X-Request-Id: dd537dd5-f6d2-4349-a3a6-699bc6d1d2f3
X-VCS-Revision: 55
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
Connection: close
Transfer-Encoding: chunked
```

**Comment by pmahnke** [comment]
@sbfl so the livepatch guys think your issue was fixed with this bug - https://bugs.launchpad.net/livepatch-auth/+bug/1639267 

are you ok now?
