### ISSUE TITLE
No Search Results for Common Term

### ISSUE THREAD

**Issue by farmrchrys** [ubuntudesign/www.ubuntu.com#1132]
## Summary
I tried to use the search feature. I searched for "virtual machine host" and "virtual machine" but both said "no results found" which seems odd.

**Comment by deadlight** [comment]
@farmrchrys : Can you please give some more information to replicate this issue? 

Searching in the top right of the page for the string "virtual machine" takes me to https://www.ubuntu.com/search?q=virtual+machine with many results [Ubuntu/Google Chrome]

Any information would help.

**Comment by nottrobin** [comment]
I'm closing this issue for now as it doesn't seem to be a problem with the website. @farmrchrys please reply if you think there is still a website issue and we can reopen it.
