### ISSUE TITLE
Incorrect link to Eclipse case study on /internet-of-things/gateways

### ISSUE THREAD

**Issue by Apeshere** [ubuntudesign/www.ubuntu.com#1138]
## Summary

the link to eclipse whitepaper is linking to a risevision casestudy on the page.
## Process

please update the link according to the web brief asap.

**Comment by barrymcgee** [comment]
@Apeshere Can you provide a link to the page which contains this error please?

**Comment by Apeshere** [comment]
sorry, forgot the link:https://www.ubuntu.com/internet-of-things/gateways

[image: Inline image 1]

**Comment by barrymcgee** [comment]
@Apeshere ..and what URL should this 'Read the whitepaper' link to?

**Comment by Apeshere** [comment]
Here below is the correct link:
http://insights.ubuntu.com/wp-content/uploads/4a5b/Eclipse-IoT-White-Paper-The-Three-Software-Stacks-Required-for-IoT-Architectures.pdf?utm_campaign=2)%20Device_FY17_IOT_Vertical_EG&utm_medium=edgegatewaycontentblock&utm_source=ubuntuwebsite&utm_content=eclipsewhitepaper

Can also be found in the web briefing here
<https://docs.google.com/document/d/1hQon1vuYPDg_GojABIwbp2gFBkE2WApZTZJGT3yUdLU/edit>

**Comment by barrymcgee** [comment]
@Apeshere Now resolved - thanks for raising this issue.
