### ISSUE TITLE
Search widget uses a seperate line when zoomed in

### ISSUE THREAD

**Issue by NeoTheThird** [ubuntudesign/www.ubuntu.com#1144]
## Summary

The search bar uses a new line and makes the navigation bar look funky.

## Process

Ubuntu 16.10, Mozilla Firefox 50.0, blocking googletagmanager.com via NoScript.

## Current and expected result

The search bar should be aligned with the rest of the navigation bar.

**Comment by nottrobin** [comment]
Thanks for reporting this @NeoTheThird. Would you be able to provide a screen shot so we can see what you're seeing?

**Comment by NeoTheThird** [comment]
There you go:

![ubuntu-search](https://cloud.githubusercontent.com/assets/12068939/20594757/b17739bc-b237-11e6-8e7f-29f11f4bc548.png)

**Comment by anthonydillon** [comment]
The only way I can reproduce this issue is to zoom in twice (125%). @NeoTheThird can you confirm this is the case?

**Comment by NeoTheThird** [comment]
Oops, sorry, I didn't notice i was zoomed in. Yes, i can confirm that. In some zoom levels, it appears in another line, in some it doesn't.

**Comment by anthonydillon** [comment]
Thanks for confirming. We officially support two levels of zoom in and out.
Therefore this is still a valid issue.
