### ISSUE TITLE
"Read instructions link" is dead

### ISSUE THREAD

**Issue by tomcallway** [ubuntudesign/www.ubuntu.com#1156]
As title. The link to Install Openstack instructionsis dead. Needs updating

**Comment by deadlight** [comment]
@tomcallway can you include a URL for whoever picks this one up, please?

**Comment by magdalena-mirowicz** [comment]
more details in this bug: Page not found on www.ubuntu.com #1165

**Comment by magdalena-mirowicz** [comment]
@tomcallway I'm closing it since we have more details in the duplicate of this bug: https://github.com/ubuntudesign/www.ubuntu.com/issues/1165
