### ISSUE TITLE
Page not found on www.ubuntu.com

### ISSUE THREAD

**Issue by sputi85** [ubuntudesign/www.ubuntu.com#1165]
## Summary
On this page: https://www.ubuntu.com/cloud/openstack
in section "Install OpenStack yourself", the link under "Read the instructions" brings up a "404, page not found error": 
https://help.ubuntu.com/lts/clouddocs/en/Intro.html?_ga=1.256531656.215527180.1475756937

**Comment by pmatulis** [comment]
The destination docs were removed because they were horribly out of date. Adjust accordingly. There is no replacement that I know of.
