### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by Ken4scholars** [ubuntudesign/www.ubuntu.com#1171]
The site automatically displays in a language based on the location which is good but sometimes you are in a location you don't know the language. I have searched and not found a way to change the documentation language to English. It displays in Russian because I am currently in the Russian Federation. Please fix this

**Comment by nottrobin** [comment]
Which page?

**Comment by Ken4scholars** [comment]
Not just one page. This page for example displays in Russian for me and no option to change language. https://help.ubuntu.com/lts/serverguide/ftp-server.html 

Sent from my Sony Xperia™ smartphone

---- Robin Winslow wrote ----

>Which page?
>

**Comment by nottrobin** [comment]
Thanks @Ken4scholars. This looks like a bug with help.ubuntu.com? This issues list is for www.ubuntu.com, and I'm afraid our team don't manage that domain.

I think the correct place to file issues with help.ubuntu.com may be here: https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs. @pmahnke do you know if that's right?

**Comment by pmahnke** [comment]
@ken4scholars - Please file the bug here: https://bugs.launchpad.net/ubuntu-doc-project/+filebug

cc @nottrobin
