### ISSUE TITLE
Education Page Top Area Text

### ISSUE THREAD

**Issue by GZhekov** [ubuntudesign/www.ubuntu.com#1190]
## Summary

The text in the top area (<section class="row row-hero strip-light">) is quite hard to read. I am using 15" laptop. See attached images - image1.png (Mozilla Firefox) and image2.png (Chromium).

## Process

Open https://www.ubuntu.com/desktop/education

## Current and expected result

See attached image3.jpeg (Windows 23" PC)

## Screenshot

![image1](https://cloud.githubusercontent.com/assets/11019878/21157074/d76db530-c180-11e6-825e-68edd44dd4e4.png)

![image2](https://cloud.githubusercontent.com/assets/11019878/21157081/dffc8992-c180-11e6-90c7-ad4b2172c984.png)

![image3](https://cloud.githubusercontent.com/assets/11019878/21157091/e677fc34-c180-11e6-83c9-c0518d5bf5f2.jpeg)

**Comment by GZhekov** [comment]
Or probably using the same background as here:
![image4](https://cloud.githubusercontent.com/assets/11019878/21157496/2b7d0990-c182-11e6-8b7b-76cf115e5896.png)

**Comment by magdalena-mirowicz** [comment]
Thank you for taking your time to report this bug. We will look into fixing it
