### ISSUE TITLE
Spotlight Event Tracking on ubuntu.com homepage

### ISSUE THREAD

**Issue by Apeshere** [ubuntudesign/www.ubuntu.com#1198]
## Summary

Suggest to update the event tag on spotlight section, so it's easier to identify traffic referred to particular insights blog content

## Process
update spotlight article link click event tag:
- update event action to {{Click Text}}
- update event label to {{Page URL}}-{{Click URL}}

## Current and expected result

Currently we see click traffic directed from spotlight to insights, but can't identify which content gets more clicks, if we can make the above change, it would be easier for device and cloud to share this section and see the benefits of spotlight.

**Comment by pmahnke** [comment]
@apeshere I didn't do exactly this, but that info in all in the updated event
