### ISSUE TITLE
Inconsistent use of "license" and "licence"

### ISSUE THREAD

**Issue by elopio** [ubuntudesign/www.ubuntu.com#1200]
## Summary

The website uses the word "license" in some places, and "licence" in others.

For example, https://www.ubuntu.com/legal/contributors

<title>Contributor license agreement | Ubuntu</title>
<h1>Canonical contributor licence&nbsp;agreement</h1>

## Process

Search for the words license and licence in the code.

## Current and expected result

Ideally, only one of the spellings should be used.
I'm not sure if legal terms in the US should use "license" and in the UK should use "licence". But if that's the case, at least it should be used consistently in the same page.

**Comment by magdalena-mirowicz** [comment]
Hi Leo, thank you for reporting. I will confirm with legal team how they want to proceed.

**Comment by magdalena-mirowicz** [comment]
We need to replace all noun occurrences of "license" with "licence"

**Comment by pmahnke** [comment]
only for nouns... verbs are licensed

**Comment by elopio** [comment]
Thank you!
