### ISSUE TITLE
Duplicated vmware logo

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/www.ubuntu.com#1201]
## Summary

Duplicated vmware logo on logo cloud.

## Process

Go to https://www.ubuntu.com/cloud/partners, scroll down to "A SELECTION OF OUR CLOUD PARTNERS"

## Current and expected result

Duplicate should be removed.

**Comment by barrymcgee** [comment]
There is no VMware logo on that page at all - cannot replicate?

**Comment by pmahnke** [comment]
@barrymcgee I can't see this still, can you confirm it is fixed?

**Comment by pmahnke** [comment]
I removed a dup vmware in partners... marking closed
