### ISSUE TITLE
Ebook download not working

### ISSUE THREAD

**Issue by ae5202** [ubuntudesign/www.ubuntu.com#1204]
## Summary

After filling out the form here: https://www.ubuntu.com/download/cloud and clicking 'download' nothing happens (the download doesn't work)

**Comment by ae5202** [comment]
After filling out the form here: https://www.ubuntu.com/download/cloud and clicking 'download' nothing happens (the download doesn't work)

**Comment by magdalena-mirowicz** [comment]
it's been fixed now
