### ISSUE TITLE
Error in "Ubuntu Advantage for servers" section

### ISSUE THREAD

**Issue by sputi85** [ubuntudesign/www.ubuntu.com#1206]
## Summary

In the table in "Ubuntu Advantage for servers" section, feature "Ceph support" should not be available as optional in Standard level of support, only in Advanced.
![screenshot from 2016-12-16 10 09 03](https://cloud.githubusercontent.com/assets/24314616/21259081/b93085d6-c377-11e6-90ad-76834c058a95.png)

## Current and expected result

Could you please remove "Optional" from the "Standard" column in the "Ceph support" row?

## Screenshot

Included in summary.

**Comment by magdalena-mirowicz** [comment]
It's been updated now: https://www.ubuntu.com/support/plans-and-pricing
