### ISSUE TITLE
Remove padding from Landscape image at /openstack/

### ISSUE THREAD

**Issue by tomcallway** [ubuntudesign/www.ubuntu.com#1214]
## Issue

Remove top and bottom padding from Landscape image on /openstack/

## Screenshot

![keyline](https://cloud.githubusercontent.com/assets/17649423/21354542/6d916980-c6c2-11e6-8fa5-64f2890bd081.png)

**Comment by magdalena-mirowicz** [comment]
@tomcallway we can't see this image on https://www.ubuntu.com/cloud/openstack

Where is it placed exactly?

**Comment by pmahnke** [comment]
@tomcallway and @magdalena-mirowicz I think he means https://www.ubuntu.com/cloud

and I think it looks ok now, we updated all the padding - 

![image](https://cloud.githubusercontent.com/assets/441217/21714986/c710aa2c-d3f9-11e6-92c7-052083da8a47.png)

agree?

**Comment by pmahnke** [comment]
@yaili can you comment?

**Comment by yaili** [comment]
It does look like it cuts off a bit abruptly at the bottom. Maybe we need to add a border bottom to the image.

**Comment by pmahnke** [comment]
@yaili how is this?

I have to do it in photoshop

![image](https://cloud.githubusercontent.com/assets/441217/21718918/84c3ba74-d412-11e6-894c-7e85e13a9cad.png)

**Comment by yaili** [comment]
Shall I do it?

**Comment by pmahnke** [comment]
@yaili sure - this was my attempt - it is resized, so I made it a bit stronger

https://assets.ubuntu.com/v1/f92adf40-screenshot-cloud_maas.png

**Comment by yaili** [comment]
Here you go: https://assets.ubuntu.com/v1/90669a61-screenshot-cloud_maas.png
