### ISSUE TITLE
OS X should be macOS

### ISSUE THREAD

**Issue by larouxn** [ubuntudesign/www.ubuntu.com#1215]
## Summary

Simple, semantic issue. As of the release of macOS Sierra 10.12.0 earlier this year, OS X is now called macOS.

## Process

Visit the [Create a USB stick on OS X | Ubuntu](https://www.ubuntu.com/download/desktop/create-a-usb-stick-on-mac-osx) page.

## Current and expected result

It said OS X but I was expecting macOS.

## Screenshot
<img width="716" alt="screen shot 2016-12-20 at 10 15 30" src="https://cloud.githubusercontent.com/assets/1557529/21355776/4a220128-c69d-11e6-8ce5-f15927c9f903.png">

**Comment by barrymcgee** [comment]
Before this change is made, would the screenshots not also need to updated as they are currently showing the wallpaper of quite an old version of OS X?

**Comment by larouxn** [comment]
Yeah, probably a good idea to update the screenshots along with the nomenclature.
