### ISSUE TITLE
/mobile/overview animation overlaps the copy

### ISSUE THREAD

**Issue by joanasa89** [ubuntudesign/www.ubuntu.com#1234]
## Summary

On desktop view animation is overlapping the copy

## Process

https://www.ubuntu.com/mobile

## Current and expected result

Animation position needs to be fixed in order to not overlap the copy

**Comment by pmahnke** [comment]
@deadlight, as an FYI,  I think Barry updated the animation CSS to fix the homepage and it likely broke this...
