### ISSUE TITLE
The button download 

### ISSUE THREAD

**Issue by ChampionGold** [ubuntudesign/www.ubuntu.com#1236]
## Summary
In this part of the website the download button has an error
https://www.ubuntu.com/download/desktop

It appears as "LTS,'eventValue'; undefined}),> Donwload"

## Process
Just click on this url and you will see it
https://www.ubuntu.com/download/desktop

## Current and expected result

well, just be careful dudes

## Screenshot

![captura de pantalla 47](https://cloud.githubusercontent.com/assets/16636678/21693937/7c31337a-d348-11e6-98d5-2f4d8a64b63a.png)

**Comment by pmahnke** [comment]
@ChampionGold thanks for filing, we have fixed this now.
