### ISSUE TITLE
Homepage spotlight link UMT tags

### ISSUE THREAD

**Issue by Apeshere** [ubuntudesign/www.ubuntu.com#1249]
## Summary

For the spotlight link and feed link, events are in place to track click rate, however, once the click through happens, the traffic performance on insights.com can't not be linked back directly with spotlight links.  

## Process

Could we have the spotlight feed link updated to: insights.ubuntu.com/tag/spotlight?utm_source=ubuntu.com&utm_medium=spotlightfeedlink&utm_campaign=Spotlight;

And for spotlight article link: is it possible to add the following UTM tags to the article link automatically when an article is tagged as a spotlight article?
UTM tag: utm_source=ubuntu.com&utm_medium=spotlightLink&utm_campaign=Spotlight

## Current and expected result

Currently, we can only see click through from spotlight, once the above UTM is implemented, we can gather more information on how well the click through traffic perform on the insight.com, bounce rate, time on page etc., information can be linked with them.

## Screeshot
![image](https://cloud.githubusercontent.com/assets/19166875/21848386/5766c424-d7f8-11e6-91f5-c4f4c81affc1.png)

**Comment by pmahnke** [comment]
We have fixed this and it will use the data from the post to push an event.

``` html
                <h3><a href="{{ item.link }}" onclick="dataLayer.push({'event' : 'GAEvent', 'eventCategory' : 'insights', 'eventAction' : 'ubuntu.com homepage spotlight article', 'eventLabel' : '{{ item.title|escapejs }}', 'eventValue' : '{{ item.link }}' });">{{ item.title }}</a></h3>
                <p><time pubdate datetime="{{ item.updated }}">{{ item.updated_datetime|date:"j F Y" }}</time></p>
```

example

``` html
<a href="https://insights.ubuntu.com/2017/02/10/webinar-getting-started-with-the-canonical-distribution-of-kubernetes/?_ga=1.58796973.1645057940.1449674517" onclick="dataLayer.push({'event' : 'GAEvent', 'eventCategory' : 'insights', 'eventAction' : 'ubuntu.com homepage spotlight article', 'eventLabel' : 'Webinar: Getting started with the Canonical Distribution of Kubernetes', 'eventValue' : 'https://insights.ubuntu.com/2017/02/10/webinar-getting-started-with-the-canonical-distribution-of-kubernetes/' });">Webinar: Getting started with the Canonical Distribution of Kubernetes</a>
```
