### ISSUE TITLE
Broken link help Ubuntu on BootOptions page

### ISSUE THREAD

**Issue by TommasoPadovan** [ubuntudesign/www.ubuntu.com#1251]
## Summary

Broken link at https://help.ubuntu.com/community/BootOptions

## Process

- Go at "https://help.ubuntu.com/community/BootOptions"
- Go to the "See Also" section.
- Link 8 (Kernel Parameters - An exhaustive list of kernel boot parameters from kernel.org) is broken.

## Current and expected result

The correct link is "https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt" and not "https://www.kernel.org/doc/Documentation/kernel-parameters.txt"

## Screenshot
--

**Comment by pmahnke** [comment]
@TommasoPadovan 

Thank you for the bug; however, you filed it against the wrong project... this is for www.ubuntu.com buts.  Documentation bugs for help.ubuntu.com should go here: https://bugs.launchpad.net/ubuntu-docs/+filebug

If you could re-report it, so they can ask you questions, please move it.

Tagging as 'invalid' here.
