### ISSUE TITLE
Ubuntu 16.04.1 LTS Lockup during USB install

### ISSUE THREAD

**Issue by lukeswr** [ubuntudesign/www.ubuntu.com#1256]
## Summary

I installed Ubuntu 16.04 LTS on a virgin box, specifically:

1) Hardware: BOXNUC5CPYH, Intel Celeron N3050 Processor, DDR3L SDRAM, Support 2.5in HDD/SSD, Gigabit Ethernet, WiFi, Bluetooth, USB 3.0, HDMI.
2) BIOS/EFI:  PYBSWCEL.86A.0058.2016.1102.1842
3) 4GB and 8GB RAM
4) 500G SATA3 HD
5) VGA console with USB keyboard. No mouse.

## Process

1) Wipe HD
2) Boot with USB 16.04 LTS d2d939ca0e65816790375f6826e4032f *ubuntu-16.04.1-server-amd64.iso (MD5) constructed with mkusb-nox on a known functional Ubuntu Server box running 16.04 LTS.
3) Walk through setup steps using defaults and connected to internet through firewall router.
4) Remove USB boot stick as instructed.

This was repeated at least 4 times with both 4GB and 8GB RAM sticks (new).

## Current and expected result

System restarts as expected. Just prior to the console login screen, the following message appears:

[ OK ] Started Dispatch Password Requests to Console Directory Watch
[ 40.123457] NMI watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [systemd-udevd:1129] 

It remains like this indefinitely. Power-cycle required.

I expected the boot to complete and the console login to appear.

NOTE: If I go to Ubuntu 16.10 server using the same system and procedure, Ubuntu 16.10 boots as expected and I can get to the console login as expected. 

## Screenshot

[ OK ] Started Dispatch Password Requests to Console Directory Watch
[ 40.123457] NMI watchdog: BUG: soft lockup - CPU#0 stuck for 22s! [systemd-udevd:1129]

**Comment by pmahnke** [comment]
@lukeswr 

You filed this bug against www.ubuntu.com.  Unfortunately we cannot move it to the [correct location](https://bugs.launchpad.net/ubuntu/+source/debian-installer) and keep you in the loop.

Can you refile it on launchpad?

Thank you,

Peter

p.s. closing it here.

**Comment by lukeswr** [comment]
Refiled as Bug #1659138 over on the Debian URL as directed above.
