### ISSUE TITLE
Cloud events on Insights not copying to u.com/cloud

### ISSUE THREAD

**Issue by tomcallway** [ubuntudesign/www.ubuntu.com#1286]
Cloud events listed onhttp://insights.u.c/cloud-and-server are not copying over to u.com/cloud

ubuntu.com/cloud events
![screen shot 2017-01-30 at 14 10 45](https://cloud.githubusercontent.com/assets/17649423/22426149/31d355bc-e6f6-11e6-962f-27fa0d3cbcd6.png)

insights.ubuntu.com/cloud-and-server events
![screen shot 2017-01-30 at 14 11 01](https://cloud.githubusercontent.com/assets/17649423/22426158/388e28b4-e6f6-11e6-8c90-5f015fabbea7.png)

---
*Reported from: https://www.ubuntu.com/cloud*

**Comment by pmahnke** [comment]
Tom

We have to manually update the /cloud page with events.

Every time we update the page, we create a card to update again when the first event expires.

It was updated 4 days ago, but only [approved yesterday and hasn't gone live yet](https://github.com/ubuntudesign/www.ubuntu.com/pull/1285). 

It looks like, in that time, you have added more events to insights.

I will update again, but if you do an update, unfortunately you will need to ping someone to manually update it.

Peter
