### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by kevin45244** [ubuntudesign/www.ubuntu.com#1314]
Link below in Reported..  Throwing 403 forbidden on all .torrent links.

---
*Reported from: https://www.ubuntu.com/download/alternative-downloads*

**Comment by pmahnke** [comment]
duplicate of #1328

there is an issue with releases not removing the GET parameter

I have filed a RT ticket with IS to look into this

**Comment by pmahnke** [comment]
We believe this has been fixed now.  Thanks for reporting.
