### ISSUE TITLE
Download link led to expired domain

### ISSUE THREAD

**Issue by 0rann1s** [ubuntudesign/www.ubuntu.com#1320]
When attempting to download Ubuntu for Desktop, I was directed to:
http://ubuntu.mirror[.]geekcdn[.]com/16.04.1/ubuntu-16.04.1-desktop-amd64.iso

Upon loading, it turned out the domain was expired. I was able to download the ISO successfully after repeating the process as I believe I was directed to a different mirror. 

Wanted to call this as it may be possible for an external party to buy the domain and host a similarly named potentially malicious file in its place. 

---
*Reported from: https://www.ubuntu.com/download/desktop/thank-you?country=US

**Comment by pmahnke** [comment]
Orannis

Thanks

I can confirm the mirror prober dropped it to unoffical on 2016-02-10 due to the domain expiry and I don't see it in the cdmirror-rss feed from LP.

https://launchpad.net/ubuntu/+mirror/geekcdn-mirror


Peter
