### ISSUE TITLE
IoT page link tagging update

### ISSUE THREAD

**Issue by Apeshere** [ubuntudesign/www.ubuntu.com#1323]
update the following link with a new tagging convention

1: Digital signage on Ubuntu  › - link update to: www.ubuntu.com/internet-of-things/digital-signage?from=iotpage
2: Robots and drones, rocking Ubuntu Core › - link update to: www.ubuntu.com/internet-of-things/robotics?from=iotpage
3: IoT gateways on Ubuntu › - link update to: www.ubuntu.com/internet-of-things/gateways?from=iotpage
4: Learn how to make a snap - link update to: snapcraft.io?from=iotpage
5: Read the AeroLion case study - link update to: pages.ubuntu.com/AerolionCS.html?from=iotpage
6: Read the Azeti Networks case study - link update to: pages.ubuntu.com/AzetiCS.html?from=iotpage
7: Learn about developing with Ubuntu Core - link update to: developer.ubuntu.com/core?from=iotpage
8: Get in Touch button - link update to: www.ubuntu.com/internet-of-things/contact-us?from=iotpage

---
*Reported from: https://www.ubuntu.com/internet-of-things*

**Comment by pmahnke** [comment]
for all these internal links... can you look at the previous page in google analytics?

**Comment by pmahnke** [comment]
April

I still don't understand what data you are looking for.

I am happy to remove all the UTM campaign information, but you could go to any of these internal pages and see how people arrived via Google Analytics

https://analytics.google.com/analytics/web/#report/content-pages/a1018242w108544136p113106543/%3Fexplorer-table.filter%3Dinternet-of-things%2Fcontact-us%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.previousPagePath%26explorer-table.advFilter%3D%5B%5B0%2C%22analytics.pagePath%22%2C%22RE%22%2C%22internet-of-things%2Fcontact-us%22%2C0%5D%5D%26explorer-table.rowStart%3D0%26explorer-table.rowCount%3D25/

What are you trying to get information on?

Peter

**Comment by Apeshere** [comment]
Hi Peter,

Basically to see where people come from as well as each link and button's
conversion rate on each page,

So need to remove utm tags, as google utm tags causing split visit counts;
same time add the additional custom tag if possible, if you think
additional custom tag is not tidy for the site I can track conversion
through events as well.

Either way , need to remove current utm tags as it is causing inaccurate
data in the reporting especially through internal links.

Thanks
