### ISSUE TITLE
Update 'logo pattern' on small screen

### ISSUE THREAD

**Issue by joanasa89** [ubuntudesign/www.ubuntu.com#1375]
## Summary
padding-bottom is too big

<img width="401" alt="screen shot 2017-02-22 at 17 24 15" src="https://cloud.githubusercontent.com/assets/21334617/23223816/f99b02f4-f923-11e6-9f8f-50d4221425bf.png">

## Current and expected result
The content should be vertically centered

**Comment by pmahnke** [comment]
what should it be?

**Comment by joanasa89** [comment]
@pmahnke 
Remove the margin-bottom from the <ul> and the margin-bottom from the last <il>
See image
<img width="400" alt="screen shot 2017-02-24 at 14 34 04" src="https://cloud.githubusercontent.com/assets/21334617/23307163/754819ca-fa9e-11e6-8278-41881c803920.png">
