### ISSUE TITLE
Using an Ubuntu 14.04 LTS, the third-party privacy opt-out form URL is broken: https://www.ubuntu.com/privacypolicy/thirdparties

### ISSUE THREAD

**Issue by a1ultima** [ubuntudesign/www.ubuntu.com#1390]
System Settings >> Details >> Legal Notice

Then the header:

> "Searching in the dash - Legal notice" 

Then the block:

> Online Search
> You may restrict your dash so that we don’t send searches to third parties and you don't receive online search results. To do this go to the Privacy panel and toggle the ‘Include online search results’ option to off. The Privacy panel can be found in your System Settings or via a dash search. For a current list of our selected third parties, please see **www.ubuntu.com/privacypolicy/thirdparties**.

But:

**www.ubuntu.com/privacypolicy/thirdparties** sends me to a 404 page.

---
*Reported from: https://www.ubuntu.com/privacypolicy/thirdparties*

**Comment by pmahnke** [comment]
Thanks for filing this.

Looks like we need to

- [ ] add a redirect from /privacypolicy/thirdparties to /legal/terms-and-policies/privacy-policy/third-parties
- [ ] update /legal/terms-and-policies/privacy-policy/third-parties to link to /legal/terms-and-policies/privacy-policy
- [ ] update /legal/terms-and-policies/privacy-policy to link to  /legal/terms-and-policies/privacy-policy/third-parties
- [ ] update the relevant copy docs
