### ISSUE TITLE
HTML Injection

### ISSUE THREAD

**Issue by mzaib1999** [ubuntudesign/www.ubuntu.com#1404]
Hi... My name is Mohammad Aurangzaib and i found  **HTML Injection vulnerability** in wiki.Ubuntu.com and i have test 135 domins of Ubuntu wiki  and all  are Vulnerable to HTML injection 
List of 135 vulnerable domains in ubuntu wiki  
  
[Home.txt](https://github.com/ubuntudesign/www.ubuntu.com/files/816173/Home.txt)

[Liked Page.txt](https://github.com/ubuntudesign/www.ubuntu.com/files/816174/Liked.Page.txt)

[membership.txt](https://github.com/ubuntudesign/www.ubuntu.com/files/816175/membership.txt)

[Release.txt](https://github.com/ubuntudesign/www.ubuntu.com/files/816176/Release.txt)

[Ubuntu Team.txt](https://github.com/ubuntudesign/www.ubuntu.com/files/816177/Ubuntu.Team.txt)

I have record a video and this is the unlisted link of my youtube video  
https://youtu.be/Zoo9QYxjwL8
---
*Reported from: https://www.ubuntu.com/support/community-support*

**Comment by pmahnke** [comment]
Mohammad

Thank you for filing this bug.

It is actually for another project, so I have filed and [ticket](https://portal.admin.canonical.com/100524) with IS to look at this and hopefully get back to you.

I am going to close the bug here.

Peter

**Comment by mzaib1999** [comment]
and what's about my repoted bug
