### ISSUE TITLE
Cloud > Openstack > Managed cloud: Not a regression but slider for number of servers doesn't work on mobile [iphone]

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/www.ubuntu.com#353]
It's already an issue on live.

Go to http://www.staging.ubuntu.com/cloud/openstack/managed-cloud

Scroll to Bootstack calculator. 
Try to use slider. 
Doesn't seem to work

**Comment by pmahnke** [comment]
@nottrobin can you apply the contribute work to fix this?

**Comment by nottrobin** [comment]
Yep that's my plan

**Comment by pmahnke** [comment]
this has been removed from the page, so closing
