### ISSUE TITLE
iot > partners: "Commercial information" - 3 blocks below - text is positioned incorrectly. Issue repeats on iot > features [iPhone/Safari]

### ISSUE THREAD

**Issue by magdalena-mirowicz** [ubuntudesign/www.ubuntu.com#358]
1. on small screen - iPhone go to: http://www.staging.ubuntu.com/internet-of-things/partners

2. scroll to Commercial information

3. Logos are showing above headings, while they should be displayed next to each other

4. Same problem on http://www.staging.ubuntu.com/internet-of-things/features within section "Setting the security standard"

**Comment by pmahnke** [comment]
Closed with  Pull request #884
