### ISSUE TITLE
Download section has too much left/right margin on small screen

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/www.ubuntu.com#624]

**Comment by deadlight** [comment]
There appear to be padding issues on the row "Ubuntu’s unique scopes bring everything..." and the footer.

**Comment by deadlight** [comment]
Demo running at: http://www.ubuntu.com-624-download-cloud-padding.demo.haus/download/cloud

Pull Request: #775

If there are any specific issues or tweaks, please give more detail and/or a screenshot.
