### ISSUE TITLE
Remove Imager.js

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/www.ubuntu.com#655]
Lets remove Imager.js and check its not used as we use srcset now.

**Comment by nottrobin** [comment]
@pmahnke nope, not related to YUI.

**Comment by anthonydillon** [comment]
Nope and infact I found a page using Imager so will need some greping when
removing.

**Comment by pmahnke** [comment]
I only found it on /about/ubuntu-font... have you found others?

**Comment by anthonydillon** [comment]
I think that was the one. Feel free to replace with a picture element and
remove Imager.
