### ISSUE TITLE
Rewrite YUI3 functions in plain JavaScript

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/www.ubuntu.com#657]
We should rewrite the functions in scratch.js to use vanilla javascript. Maybe even ES6 and use babel on build to convert to ES5 with minification. If that is a step to far, use the jQuery we have loaded on the pages to manipulate the DOM. Either way the js should be minified so will need to pass a build step. Is this something that asset server @nottrobin?

**Comment by nottrobin** [comment]
It looks like there's a consensus here that we should use vanilla JavaScript over jQuery, so I've updated the title.

No the Assets Server can't help here. It it not intended for dynamic JavaScript files in general (by which I mean ones that are being constantly changed), and definitely shouldn't be hosting bespoke JavaScript for a single website. `scratch.js` (or hopefully a new file with a more descriptive name) should be kept local.

**Comment by pmahnke** [comment]
I think we did this... so closing
