### ISSUE TITLE
HTTP error 403 on fetching ressource via apt-get install python3-pip

### ISSUE THREAD

**Issue by 4383** [ubuntudesign/www.ubuntu.com#748]
## Context

When I try to install python3-pip via package manager (apt-get) I obtain an HTTP error 403.

## Process

1. Update system `sudo apt-get update`
2. Install python3-pip `sudo apt-get install python3-pip`

## Expected result

I expect a return 0 (success) from package manager when I try to install

## Current result
Error details :
```
Err http://fr.archive.ubuntu.com/ubuntu/ trusty-updates/universe python-chardet-whl all 2.2.1-2~ubuntu1
  403  Forbidden [IP: 194.158.119.190 80]
E: Failed to fetch http://fr.archive.ubuntu.com/ubuntu/pool/universe/c/chardet-whl/python-chardet-whl_2.2.1-2~ubuntu1_all.deb  403  Forbidden [IP: 194.158.119.190 80]
```

**Comment by nottrobin** [comment]
This looks like a bug with the operating system. This project is only about the website www.ubuntu.com website, and is for filing issues or feature requests for the website.

To learn how to file a bug with the operating system, please refer to [the reporting bugs page](https://help.ubuntu.com/community/ReportingBugs).
