### ISSUE TITLE
Update UASD

### ISSUE THREAD

**Issue by chrisjohnston** [ubuntudesign/www.ubuntu.com#757]
With the release of the new pricebook, we have an updated service description which needs to be released please.

http://www.ubuntu.com/legal/ubuntu-advantage/service-description

All of the changes needed are shown using suggestion mode in the docs:

https://docs.google.com/document/d/1JuxYXtJOdXwe7MbV1JlQmStUfRKakVR3Tjo6y0p5XqY/edit
https://docs.google.com/document/d/1Z-L0noGit7HrKOMIy_Yi4_V7o42bgMnhsuK_10cIefw/edit#
https://docs.google.com/document/d/1QWadKPq0SuHOG-NfjZ1PZg4NlBLlGiyyHJfVf8z5o_4/edit
https://docs.google.com/document/d/1DK2w_92ONDODQp4T3w5eJYf-nrZD8f-G0PazadcPtw8/edit

**Comment by grahambancroft** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;RvL7lYrp&#x2F;1400-update-uasd"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Update UASD</a>

**Comment by grahambancroft** [comment]
Hi Chris,

The changes are live.

All the best,

Graham
