### ISSUE TITLE
Update OpenStack AutoPilot page for 16.04

### ISSUE THREAD

**Issue by jbicha** [ubuntudesign/www.ubuntu.com#763]
## Context

http://www.ubuntu.com/download/cloud/install-openstack-with-autopilot

## Expected result

The instructions should be for Ubuntu Server 16.04 LTS.

## Current result

The instructions are for Ubuntu Server 14.04 LTS.

**Comment by jbicha** [comment]
See [this commit](https://github.com/ubuntudesign/www.ubuntu.com/commit/6bc40ff368094a387a90997d2b71bfe39dd06bab).

**Comment by pmahnke** [comment]
jbicha

thanks for filing the bug, but the commit was actually to pin autopilot to Ubuntu 14.04 for now.   the team is working on the 16.04 version, but it isn't live yet.

best regards,

peter
