### ISSUE TITLE
Ubuntu server download page has wrong name in the Release Names url

### ISSUE THREAD

**Issue by xnox** [ubuntudesign/www.ubuntu.com#772]
http://www.ubuntu.com/download/server should have "16.04.1 LTS" in the "release notes" url

**Comment by magdalena-mirowicz** [comment]
@xnox Just to confirm: it's only the wording of the link that should change, isn't it? (To include 16.04.1) Is the link itself correct?

Also, should it only be updated on server page? For example same link exists here: http://www.ubuntu.com/download/desktop

If any other places should be updated could you send me full list? Thanks!

**Comment by xnox** [comment]
Actually, I think we can keep things as it is.

"Ubuntu 16.04 LTS release notes" -> point to actual release notes for the whole series with separate sections for "16.04"(.0) and specific things about "16.04.1" release, etc. Because we do simply update them. This is similar to other documentation links e.g. "Ubuntu 16.04 LTS help" etc, which also remain valid point release or not.

Actually, nothing to change here I think. Sorry for the noise.
