### ISSUE TITLE
lubuntu.net -> lubuntu.me on http://www.ubuntu.com/download/ubuntu-flavours

### ISSUE THREAD

**Issue by tsimonq2** [ubuntudesign/www.ubuntu.com#780]
The Lubuntu team has changed it's website from http://lubuntu.net/ to http://lubuntu.me/ and http://www.ubuntu.com/download/ubuntu-flavours needs to be updated appropriately.

If you need proof of the change, I can provide it.

**Comment by pmahnke** [comment]
simon, I have seen the Launchpad bug, so no proof required - peter
