### ISSUE TITLE
Certification section has bad global styling

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/www.ubuntu.com#784]
I know this is not part of this project but as a web team we should care about this section.

The global nav on small screens is displaying all list as block items.

**Comment by nottrobin** [comment]
Can you provide a screen shot? For me, the global nav simply disappears on small screens across the whole site including the certification section (although that orange section in the main nav isn't ideal):

![certification/desktop](http://i.imgur.com/9BzoSt9.png)

**Comment by anthonydillon** [comment]
Your right sorry, can not replicate.
