### ISSUE TITLE
Most "@ubuntu.com" address (if not all) do not use TLS

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [ubuntudesign/www.ubuntu.com#785]
I was just logging into the Ubuntu Wiki site when I noticed that the password reset email sent to me from `noreply@ubuntu.com` was not using TLS (I have blacked out personal information):

![ubuntu_one_password_reset_email_not_encrypted_message](https://cloud.githubusercontent.com/assets/11575271/17275982/7c26cc6c-5712-11e6-9f2e-574e8b87bb6a.png)

I also noticed that the email notifying me of changes to a Wiki page from the same address wasn't using TLS. Now this would be more acceptable because it was only notifying me of changes to a Wiki page. But I would still prefer it if all of them did use TLS. And in terms of the password reset email not using TLS, now that is really a bad security practice, I don't want my password reset emails sent to me in plain-text over the internet.

I don't know if this issue affects other `@ubuntu.com` addresses, but whether it does or it doesn't, they really all should be made to use it.

I hope that this is the right place to report this issue to, if it is not then please direct me in the right direction.

**Comment by anthonydillon** [comment]
We've enabled outbound TLS from the mail relay used by SSO to the remote
mail servers, that should address the issue sufficiently.

**Comment by SeventhSonOfASeventhSon** [comment]
This appears to have fixed the issue.
