### ISSUE TITLE
Add 'Blog' link to /cloud

### ISSUE THREAD

**Issue by tomcallway** [ubuntudesign/www.ubuntu.com#794]
## Context

Want to make it easier for /cloud visitors to access the Cloud blog on Insights
## Process
1. User goes to /cloud
2. Wants to read blog content - Clicks 'Blog' link
3. Goes to /cloud/blog > http://insights.ubuntu.com/cloud-and-server
## Expected result

Increase in traffic to http://insights.ubuntu.com/cloud-and-server and greater exposure of premium content
## Current result

We have a hidden 'Insights' link in the global nav bar and current news items on the homepage. This link will be available anywhere and use descriptive labelling

**Comment by pmahnke** [comment]
please hold for now

**Comment by pmahnke** [comment]
removing this until we are ready
