### ISSUE TITLE
paste.ubuntu.com

### ISSUE THREAD

**Issue by md-5** [ubuntudesign/www.ubuntu.com#799]
Sincerest apologies - I know this isn't the correct place, but IRC has been unable to assist with finding that place.
Where might I get in touch with the paste.ubuntu.com people?
We've had our app paste error logs there for a number of years, but it now seems to be caught up from an overzealous spam filter.

Thanks

**Comment by pmahnke** [comment]
md-5  I asked IS, they say you should file on https://bugs.launchpad.net/canonical-pastebin/+filebug

I hope that helps... ping us here again if that doesn't work.
