### ISSUE TITLE
ubuntu.com - guidelines - 31 May 2013 within Marketo needs update

### ISSUE THREAD

**Issue by Apeshere** [ubuntudesign/www.ubuntu.com#805]
## Summary

The current ubuntu.com guidelines within Marketo with the latest css needs some update on the IOT section or the old things section, this guideline template is currently being used on multiple forms landing pages, and it is not reflecting the current live ubuntu.com site main nav.

## Current and expected result
- Things nav button should be changed to IOT to reflect the current site
- Need to include digital signage page within the IOT main navigation menu as a secondary nav button

## Screenshot
![image](https://cloud.githubusercontent.com/assets/19166875/17738998/76a8bc2e-648b-11e6-9ba5-77b496e842f2.png)

**Comment by pmahnke** [comment]
I updated the orange bar menu; however, I think you will need to re-approve each template that uses it individually and make sure it all works.

Peter

**Comment by Apeshere** [comment]
With new vertical page, we need to update this template again. 
![image](https://cloud.githubusercontent.com/assets/19166875/19233068/1e315ff4-8edb-11e6-959f-462052855906.png)
