### ISSUE TITLE
http://www.ubuntu.com/desktop/snappy first nav button wrong

### ISSUE THREAD

**Issue by Apeshere** [ubuntudesign/www.ubuntu.com#807]
## Summary

when you are on http://www.ubuntu.com/desktop/snappy, the main navigation chain started with Cloud instead of desktop, so need to change the Cloud to Desktop on the nav bar for this page

## Current and expected result

update nav bar on page http://www.ubuntu.com/desktop/snappy, change first button from Cloud to Desktop

## Screenshot
![image](https://cloud.githubusercontent.com/assets/19166875/17743879/4f751c44-649d-11e6-9632-571a163ed754.png)

**Comment by pmahnke** [comment]
Apeshere

Thanks for filing an issue... I will get on it right away.

Peter

**Comment by pmahnke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;998RTzfM&#x2F;1651-update-of-the-section-title-for-desktop-snappy"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> update of the section_title for &#x2F;desktop&#x2F;snappy</a>
