### ISSUE TITLE
Titles in latest news and events in /cloud too large

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/www.ubuntu.com#809]
## Summary

On the cloud landing page in the latest news and events page, the events titles are too large.

## Process

1. Visit http://www.ubuntu.com/cloud
2. Scroll down to the "The latest Ubuntu Cloud news and events" section

## Current and expected result

The events headings are h3, as in the news headings, but are larger. They should be the same size as the news column headings.

**Comment by pmahnke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;32V1RfiM&#x2F;1633-bug-fix-typography-of-news-and-events-on-cloud"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [bug] fix typography of news and events on &#x2F;cloud</a>

**Comment by pmahnke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;km2JPDeR&#x2F;1637-review-screen-images-for-issue-fix"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> review screen images for issue fix</a>
