### ISSUE TITLE
Payment Getway

### ISSUE THREAD

**Issue by enesdemir** [ubuntudesign/www.ubuntu.com#812]
## Summary
Hi; I am an developer from Turkey, I want to support ubuntu. There is only paypal payment method. Unfourtuantly paypal can't give any services for Turkey. 

## Process
1- I try to download ubuntu
2- I saw some services and I want to buy it.
3- But there is only paypal method(which one is not exsist in Turkey)

## Current and expected result

I can't buy or support...

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
enesdemir

thanks for trying to contribute, we know paypal isn't the greatest and we have a plan to replace it at some point, it just hasn't been very high on our list of priorities.

perhaps you could help in some other way through the community? see http://community.ubuntu.com/contribute/ for some ideas.

I am going to close this issue for now, but when we get around to fixing up contributions, I will try and let you know.

Peter
