### ISSUE TITLE
Partner programme capitalisation needs to be consistent

### ISSUE THREAD

**Issue by ellenarnold** [ubuntudesign/www.ubuntu.com#814]
## Summary

We need to be consistent with the capitalisation used in our partner programmes.  According to the copy guidelines and agreed with Tom, we should only capitalise product names.  There are a few places that need to be updated on our partners site: 

OpenStack Interoperability Lab should be OpenStack interoperability lab
Charm Partner Programme should be Charm partner programme
Ubuntu Channel Partner Programme should be Ubuntu channel partner programme

**Comment by pmahnke** [comment]
@ellenarnold I filed this on the partners issue tracker, but it effects /cloud/partners as well, so I will fix that.

**Comment by pmahnke** [comment]
@ellenarnold what about 'Ubuntu Certified Public Cloud programme'? 'Ubuntu certified public cloud programme' I assume?

**Comment by pmahnke** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;LhCVYhIt&#x2F;1652-update-capitalisation-of-cloud-partner-programmes"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> update capitalisation of cloud partner programmes</a>
