### ISSUE TITLE
rufus website has a lot of spam "Download" links 

### ISSUE THREAD

**Issue by BryanQuigley** [ubuntudesign/www.ubuntu.com#816]
## Summary

Download page for Rufus USB Installer linked from http://www.ubuntu.com/download/desktop/create-a-usb-stick-on-windows has a lot of spam "Download Links"

## Process

Pretend you are a new user who wants to try out Ubuntu.
1.  You get to http://www.ubuntu.com/download/desktop/create-a-usb-stick-on-windows
2. You follow the instructions to get to rufus website.

## Current and expected result

Currently:  You click the big Download (possibly spyware) link instead of what you actually want.
Expected: we provide clear instructions without ads to get in the way.

## Screenshot
![rufus_website](https://cloud.githubusercontent.com/assets/702754/17899640/f1ddc18a-6929-11e6-9a35-7d44db99beaf.png)

**Comment by deadlight** [comment]
I think that we used to recommend http://unetbootin.github.io/
I remember there being a particular reason that we stopped recommending it; is that still valid?

**Comment by nottrobin** [comment]
I'm not sure what we should be doing about this. If we're recommending Rufus, the only faithful thing to do in my opinion is to send the user to Rufus's official download page. If the experience on that page is bad, I think our best option really is to stop recommending Rufus. Unless there's another place to download Rufus which is just as official?

However I imagine there was probably a very good reason for recommending Rufus. Different bootable USB creators work more or less well with different ISOs and on different systems, so I assume Rufus is simply more reliable in this context.

I think our options are:

- look for a nicer but still official download page
- try asking Rufus to make their page nicer
- see if there is a tool that fits better than Rufus (this would require significant testing)

**Comment by pmahnke** [comment]
We moved to rufus because of similar, or worse issues on pendrivelinux.com

The ads on rufus are google ads and change and aren't always misleading.

![image](https://cloud.githubusercontent.com/assets/441217/17927230/8cf1b54c-69ec-11e6-98e6-824554394f79.png)

I have asked Will Cooke to look into something better, so I am going to close this for now.

Thanks,

Peter
