### ISSUE TITLE
tweets from insights.u.c should automatically include the first image

### ISSUE THREAD

**Issue by janesillber** [ubuntudesign/www.ubuntu.com#820]
## Summary

When tweeting a link from insights.u.c, it would be better if the tweet  automatically includes the main image.  Is that an option that can be turned on in the sharing plugin?

**Comment by deadlight** [comment]
Hi @janesillber, insights is still on launchpad, as it's a separate project.

I'm going to close this issue but I've copied it over, where it'll be auctioned:
https://bugs.launchpad.net/resource-centre/+bug/1617391

Thanks,
Karl
