### ISSUE TITLE
Typo on release cycle graph

### ISSUE THREAD

**Issue by Odaeus** [ubuntudesign/www.ubuntu.com#825]
## Summary

The word "maintenance" is spelled incorrectly on the release cycle diagram on this page: http://www.ubuntu.com/server

## Screenshot

![ubuntu server - for scale out workloads ubuntu 2016-09-06 22-26-20](https://cloud.githubusercontent.com/assets/2150/18289815/499944aa-7481-11e6-91f6-992488a0825d.png)

**Comment by nottrobin** [comment]
Thanks for reporting this @Odaeus.

@pmahnke didn't we fix this once already? Or was that on a similar graphic on a different page?
