### ISSUE TITLE
Desktop partners page missing partnerLogoClouds

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/www.ubuntu.com#828]
## Summary
The desktop partners page is reporting an error of `partners.js?v=d4d4fe6:21 Uncaught ReferenceError: partnerLogoClouds is not defined`

## Process
- Go to http://www.ubuntu.com/desktop/partners
- Look at the console and see the error

### Current
- No partner logo cloud is displayed

### Expect 
- Partner logo cloud to be displayed

**Comment by pmahnke** [comment]
@anthonydillon currently that page is working

![image](https://cloud.githubusercontent.com/assets/441217/18616044/e10da7e8-7dac-11e6-871f-2b911c562a45.png)

perhaps we need to look at making it more bullet proof to partners being offline?

**Comment by anthonydillon** [comment]
Sorry, what is the issue? The desktop logos are missing?

**Comment by pmahnke** [comment]
@anthonydillon you filed the bug... that the logos were missing with a JS error... I think it was intermittent... as I see them now.

**Comment by anthonydillon** [comment]
Oh might have been resolved with the new js work.

**Comment by pmahnke** [comment]
Closing then... reopen if we see issues
