### ISSUE TITLE
Use juju-cards for /cloud/juju

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/www.ubuntu.com#829]
## Summary
There is a bundle section on the juju page which displays a list of cards previewing bundles. These should be replaced with juju-cards.

## Process
- Replace each div with the juju-card div and a single include of the script above them
- Use https://jujucharms.com/community/cards to help

### Current
- Hard coded bundle cards

### Expected
- Use the juju-card project to load the data from the API

**Comment by pmahnke** [comment]
I attempted to do this, but they did not work at all.  After the YUI removal, we should look again.
