### ISSUE TITLE
Breadcrumbs styling is broken

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/www.ubuntu.com#834]
I noticed the breadcrumbs look broken in master (not in live). We should fix this before it gets released.

![broken breadcrumbs](http://i.imgur.com/fHqDp53.png)

**Comment by anthonydillon** [comment]
It got released.

**Comment by pmahnke** [comment]
@nottrobin is this still an issue? looks good to me

**Comment by nottrobin** [comment]
@pmahnke yep I definitely still see it on live. I think @anthonydillon should be able to reproduce it.
