### ISSUE TITLE
Broken styling in desktop breadcrumbs

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/www.ubuntu.com#835]
## Summary
- The breadcrumbs section has to much top padding on full width desktop pages

## Process
- Go to http://localhost:8001/phone
- See that the breadcrumb is not evenly padded top and bottom

## Current and expected result
- The `after` element is not being hidden on large screens

**Comment by nottrobin** [comment]
@anthonydillon was my issue not good enough? https://github.com/ubuntudesign/www.ubuntu.com/issues/834

**Comment by anthonydillon** [comment]
Beat me to it.
