### ISSUE TITLE
http://www.ubuntu.com/tablet

### ISSUE THREAD

**Issue by dfsfdfgghfhdfhd** [ubuntudesign/www.ubuntu.com#843]
## Summary

In the page "tablets," the "buy now" link is not working. 

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include
![tablets](https://cloud.githubusercontent.com/assets/22107713/18404229/31ceac60-769e-11e6-9844-1e4a8961d49a.png)
 a screenshot]

**Comment by nottrobin** [comment]
Very true. We fixed #836 for the http://www.ubuntu.com/tablet/devices page but missed this one. We'll get this seen to ASAP.
