### ISSUE TITLE
Delete unused javascript files

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/www.ubuntu.com#847]
At least `static/js/custom/mrkto-toggle.js` and `static/js/custom/demo-patterns.js` appear to be unused throughout the site. Could we delete them? And if we can find and remove any other unused JS that would be great.

**Comment by nottrobin** [comment]
On a related note, what's this directory doing here?
https://github.com/ubuntudesign/www.ubuntu.com/tree/master/templates/patterns-assets

**Comment by pmahnke** [comment]
I see that static/js/custom/demo-patterns.js is a mirror of templates/patterns-assets/js/patterns.js which is what your related note refers to...
