### ISSUE TITLE
404 on top result from duckduckgo

### ISSUE THREAD

**Issue by budmc29** [ubuntudesign/www.ubuntu.com#852]
## Summary

visit [duckduckgo.com](duckduckgo.com)

## Process

search for "how to run a ssh server in ubuntu"
click first result
[https://help.ubuntu.com/10.04/serverguide/openssh-server.html](https://help.ubuntu.com/10.04/serverguide/openssh-server.html)

## Current and expected result

expecting to see the information related to the topic
instead I get a 404 page

**Comment by nottrobin** [comment]
Thanks for filing this @bugmc29. Unfortunately I fear this is simply a peril of having a wiki. But maybe they have the facility to set up redirects for important URLs, I'm not sure.

Would you mind filing this bug over in [their bug system](https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs), they can tell you if this can be addressed much better than I can.

**Comment by nottrobin** [comment]
Oh sorry I see that part of the site isn't a wiki. In any case, we are not the team who looks after help.ubuntu.com. If you get this filed over in their bug system hopefully they can address it promptly.
