### ISSUE TITLE
Cloud pie chart text misaligned

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/www.ubuntu.com#853]
On http://www.ubuntu.com/cloud, in the "Use Ubuntu on certified public clouds" row, the pie chart looks like this in Chrome:

![misaligned](http://i.imgur.com/RCyI15D.png)

It looks better but still misaligned on Firefox.

**Comment by anthonydillon** [comment]
Looks ok now.
![openstack cloud ubuntu](https://cloud.githubusercontent.com/assets/1413534/18663164/48263b66-7f15-11e6-8abb-711f4c4b8037.png)

@nottrobin can you confirm please?

**Comment by pmahnke** [comment]
I did fix... closing
