### ISSUE TITLE
Replace versions with latest 16.04 links

### ISSUE THREAD

**Issue by gmeszaros** [ubuntudesign/www.ubuntu.com#887]
## Summary

Just noticed that the links point to 14.04 release, it would be better to have them direct you to 16.04. 

Thanks for considering,
Gábor

**Comment by pmahnke** [comment]
@gmeszaros thanks for filing an issue, but could you give us more details as to which links are pointing to 14.04?

thanks,

Peter

**Comment by gmeszaros** [comment]
Hello @pmahnke, I was under the impression that reporting a bug includes the source page automatically. (It'd be best, but that's a side idea).
So on page [http://www.ubuntu.com/download/cloud](http://www.ubuntu.com/download/cloud)
step 1, Set up your hardware -> Install Ubuntu Server 14.04 LTS on one of the machines with two network interfaces.

Let me know if it's still not enough detail.

Regards,
Gabor

**Comment by pmahnke** [comment]
@gmeszaros can github links pass that info to an issue?  I would love to do that.

also, I checked with the Autopilot guys and it currently only works with 14.04 for now.  If you are trying to install a 16.04 cloud, perhaps look at the links at the bottom of that page using conjure-up or via juju.

Peter
