### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by chrisjohnston** [ubuntudesign/www.ubuntu.com#903]
## Summary

Invalid link to support portal

## Process

http://www.ubuntu.com/management/ubuntu-advantage
find Support portal login ›

## Current and expected result

Redirects to what I assume is the old portal, which no longer works. Please change url to https://support.canonical.com

**Comment by chrisjohnston** [comment]
Please search to see if there are any other references to the old portal URL

**Comment by pmahnke** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Invalid link to support portal](https://trello.com/c/dsVLeufZ/1859-invalid-link-to-support-portal)
