### ISSUE TITLE
The Phone link on the main page doesn't work

### ISSUE THREAD

**Issue by davmor2** [ubuntudesign/www.ubuntu.com#910]
## Summary

If you navigate to ubuntu.com and scroll down to Multiple Devices one experience and then click on it it does nothing if you right click on it and select open in another tab it then opens

## Process

1. open a browser (Tested in ubuntu-browser, firefox and chromium)
2. goto ubutnu.com
3. click on Multiple Devices one experience
4. right click on it and select open in another tab

## Current and expected result

I expect the page to open in the current tab
Actual result nothing happens unless I right click on select open in another tab

**Comment by nottrobin** [comment]
Confirmed. If you go to the homepage <http://www.ubuntu.com/> and click the "Multiple devices one experience >" link, nothing happens. Unless you turn off JavaScript.

Clearly one of our trackers is hijacking the click and not handling it faithfully. I'll try to track down which one.

**Comment by nottrobin** [comment]
I've tracked down the problem - it's [this line](https://github.com/ubuntudesign/www.ubuntu.com/blob/master/static/js/scratch.js#L71). I'll submit a PR to remove it.
