### ISSUE TITLE
shop.ubuntu.com invalid TLS certificate

### ISSUE THREAD

**Issue by bardiharborow** [ubuntudesign/www.ubuntu.com#913]
The server for `shop.ubuntu.com` presents a certificate for `shop.canonical.com`, resulting in a TLS error. It should present a valid certificate.

Apologies if this is the incorrect place to report this.

Kudos to [rinzwind](https://askubuntu.com/users/15811/rinzwind) for [reporting this](https://chat.stackexchange.com/transcript/message/32705460#32705460)  over at askubuntu.chat.SE.

**Comment by nottrobin** [comment]
Thanks @bardiharborow. We'll find out how to get this fixed.

It looks to me like the content of shop.ubuntu com is identical to shop.canonical.com, and so shop.ubuntu.com should probably be redirected there.

But even for that to work properly we'd need to add shop.ubuntu.com into the certificate.

**Comment by pmahnke** [comment]
I have emailed Merchandise Mania to see if they can fix.

**Comment by pmahnke** [comment]
@bardiharborow I have been told this is now fixed.  please let me know if you still have problems
