### ISSUE TITLE
Broken title

### ISSUE THREAD

**Issue by KIKEDIZAblah** [ubuntudesign/www.ubuntu.com#925]
This page:
https://www.ubuntu.com/download/desktop/install-ubuntu-desktop
Has the title "Install Ubuntu 16.04 &lt;abbr title="long-term support"&gt;LTS&lt;/abbr&gt; | Ubuntu", which has the inner HTML of the h1 at the top of the page.

At least to me, the html can be seen clearly in the title of the tab in my browser.

**Comment by WillMoggridge** [comment]
Thanks for pointing this out!
