### ISSUE TITLE
UASD wrong link

### ISSUE THREAD

**Issue by chrisjohnston** [ubuntudesign/www.ubuntu.com#931]
## Summary

Thanks for the recent update to the service description. I found multiple link issues on the updated page:

https://www.ubuntu.com/legal/ubuntu-advantage/service-description
## KVM support
1. Search for 'Unlimited Ubuntu KVM guest support'
2. Click the link
Current: redirected to the portion explaining LXD support
Expected: redirected to the portion explaining KVM support

## Landsape Management
Find Landscape Management (see Section 2.5) and click the link to section 2.5
Current: redirects to 2.5 of the support process, which doesn't talk about Landscape
Expected: redirects to 2.5 of the service description, which does talk about Landscape.

## Ubuntu Legal Assurance programme (see Section 5)
Find Ubuntu Legal Assurance programme (see Section 5) and click the link
Current: Redirects to languages
Expected: Redirects to the legal assurance programme

## 10x5 support
Find 10x5 phone and ticket support for all packages in Ubuntu main (see Section 3), except as defined in this section
Click "this section"
Current: redirected to data about UA Server Essential
Expected: redirected to data about UA Server Standard

## 24x7 support
Find universe, except as defined in this section
Click "this section"
Current: redirected to data about UA Server Essential
Expected: redirected to data about UA Server Advanced

**Comment by pmahnke** [comment]
Chris, we will fix this up, but in the future, it would be helpful to have this better documented in the copy doc than 'see below' which only works for print.
